/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programdbsenin22_tugas;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.sql.Statement; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 

/**
 *
 * @author kalvi
 */
public class DeleteData extends javax.swing.JFrame {
  String user="root";         
  String pswd ="";         
  String host="localhost";         
  String db="dbdatasenin";         
  String url="";         
  private Connection Lconnection=null;
    /**
     * Creates new form DeleteData
     */
    public DeleteData() {
        initComponents();
        btnhapus.setEnabled(false);
        try { 
        Class.forName("com.mysql.jdbc.Driver");             
        url="jdbc:mysql://"+ host +"/"+ db +"?user=" + user + "&password="+ pswd; 
        Lconnection=DriverManager.getConnection(url);         
    } 
    catch(ClassNotFoundException e) {             
        System.out.println("Driver tidak ditemukan");         
    } 
    catch (SQLException e){             
        System.out.println("koneksi gagal:" + e.toString());                
    }
  }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLNAME1 = new javax.swing.JLabel();
        LBLNAME2 = new javax.swing.JLabel();
        LBLTELEPHONE = new javax.swing.JLabel();
        LBLTELEPHONE2 = new javax.swing.JLabel();
        LBLTELEPHONE1 = new javax.swing.JLabel();
        LBLTELEPHONE4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        txtprodi = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        btncekid = new javax.swing.JButton();
        btnceknama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        LBLNAME1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME1.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME1.setText("ID");

        LBLNAME2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME2.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME2.setText("Nama");

        LBLTELEPHONE.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE.setText("Alamat");

        LBLTELEPHONE2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE2.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE2.setText("Telepon");

        LBLTELEPHONE1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE1.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE1.setText("Handphone");

        LBLTELEPHONE4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE4.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE4.setText("Prodi");

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncekid.setText("Cek ID");
        btncekid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekidActionPerformed(evt);
            }
        });

        btnceknama.setText("Cek Nama");
        btnceknama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceknamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LBLNAME1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addGap(18, 18, 18))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LBLNAME2)
                            .addGap(54, 54, 54)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLTELEPHONE4)
                            .addComponent(LBLTELEPHONE1)
                            .addComponent(LBLTELEPHONE2)
                            .addComponent(LBLTELEPHONE))
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txthp, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtprodi, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnceknama, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncekid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLNAME1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncekid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLNAME2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnceknama))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLTELEPHONE2)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE1)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE4)
                    .addComponent(txtprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnhapus)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pStatement = Lconnection.prepareStatement
            ("DELETE FROM tbdatasenin WHERE Id=?");
            pStatement.setString(1, txtid.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog (this,"Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog (this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            txtnama.setText("");
            txtalamat.setText("");
            txttelepon.setText("");
            txthp.setText("");
            txtprodi.setText("");
            txtid.setText("");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncekidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekidActionPerformed
        // TODO add your handling code here:

        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from tbdatasenin" + " where Id ='" + txtid.getText() + "'");

            if (rs.next()) {
                btnhapus.setEnabled(true);
                txtnama.setText(rs.getString("Nama"));
                txtalamat.setText(rs.getString("Alamat"));
                txttelepon.setText(rs.getString("Telepon"));
                txthp.setText(rs.getString("Handphone"));
                txtprodi.setText(rs.getString("Prodi"));
                txtid.setText(rs.getString("Id"));
            }
            else {
                JOptionPane.showMessageDialog(this,"Id : Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btnhapus.setEnabled(false);
                txtnama.setText("");
                txtalamat.setText("");
                txttelepon.setText("");
                txthp.setText(""); 
                txtprodi.setText("");      
                txtid.setText("");
                txtnama.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btncekidActionPerformed

    private void btnceknamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceknamaActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery ("Select * from tbdatasenin" + " where Nama like('%" + txtnama.getText() + "%')");

            if (rs.next()) {
                btnhapus.setEnabled(true);
                txtnama.setText(rs.getString("Nama"));
                txtalamat.setText(rs.getString("Alamat"));
                txttelepon.setText(rs.getString("Telepon"));
                txthp.setText(rs.getString("Handphone"));
                txtprodi.setText(rs.getString("Prodi"));
                txtid.setText(rs.getString("Id"));
            }
            else {
                JOptionPane.showMessageDialog(this,"Id : Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btnhapus.setEnabled(false);
                txtnama.setText("");
                txttelepon.setText("");
                txthp.setText("");
                txtalamat.setText("");
                txtid.setText("");
                txtprodi.setText("");
                txtnama.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnceknamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLNAME1;
    private javax.swing.JLabel LBLNAME2;
    private javax.swing.JLabel LBLTELEPHONE;
    private javax.swing.JLabel LBLTELEPHONE1;
    private javax.swing.JLabel LBLTELEPHONE2;
    private javax.swing.JLabel LBLTELEPHONE4;
    private javax.swing.JButton btncekid;
    private javax.swing.JButton btnceknama;
    private javax.swing.JButton btnhapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtprodi;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
