/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programdbsenin22_tugas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author kalvi
 */

public class SimpanData extends javax.swing.JFrame {

    /**
     * Creates new form SimpanData
     */
    public SimpanData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLNAME = new javax.swing.JLabel();
        LBLTELEPHONE3 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        LBLNAME1 = new javax.swing.JLabel();
        LBLTELEPHONE = new javax.swing.JLabel();
        LBLTELEPHONE1 = new javax.swing.JLabel();
        LBLTELEPHONE2 = new javax.swing.JLabel();
        LBLTELEPHONE4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        txtprodi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        LBLNAME.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME.setText("Nama");

        LBLTELEPHONE3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE3.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE3.setText("Telepon");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        LBLNAME1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME1.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME1.setText("Nama");

        LBLTELEPHONE.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE.setText("Alamat");

        LBLTELEPHONE1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE1.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE1.setText("Handphone");

        LBLTELEPHONE2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE2.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE2.setText("Telepon");

        LBLTELEPHONE4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE4.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE4.setText("Prodi");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBLNAME1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLTELEPHONE4)
                            .addComponent(LBLTELEPHONE2)
                            .addComponent(LBLTELEPHONE)
                            .addComponent(LBLTELEPHONE1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(txttelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(txthp)
                        .addComponent(txtprodi)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLNAME1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLTELEPHONE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE2)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE1)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE4)
                    .addComponent(txtprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user="root";         
        String pswd ="";         
        String host="localhost";         
        String db="dbdatasenin";         
        String url=""; 
        
        try {
             Class.forName("com.mysql.jdbc.Driver");
        url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
        Connection conn=DriverManager.getConnection(url);
        PreparedStatement pStatement = conn.prepareStatement("INSERT INTO tbdatasenin (Nama,Alamat,Telepon,Handphone,Prodi)" + "VALUES (?,?,?,?,?)");
        
        pStatement.setString(1, txtnama.getText());    
        pStatement.setString(2, txtalamat.getText());
        pStatement.setString(3, txttelepon.getText());             
        pStatement.setString(4, txthp.getText()); 
        pStatement.setString(5, txtprodi.getText());
        
        if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
            "Penambahan sukses", "Informasi",
            JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,
            "Penambahan gagal", "Informasi",
            JOptionPane.INFORMATION_MESSAGE);
        
            pStatement.close();
            conn.close();
            
            txtnama.setText("");
            txtalamat.setText("");
            txttelepon.setText("");
            txthp.setText("");
            txtprodi.setText("");   
            }
        
            catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
            }
            catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
            }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpanData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLNAME;
    private javax.swing.JLabel LBLNAME1;
    private javax.swing.JLabel LBLTELEPHONE;
    private javax.swing.JLabel LBLTELEPHONE1;
    private javax.swing.JLabel LBLTELEPHONE2;
    private javax.swing.JLabel LBLTELEPHONE3;
    private javax.swing.JLabel LBLTELEPHONE4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnama1;
    private javax.swing.JTextField txtprodi;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
